"""
Django settings for orthanc project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load Orthanc/.env (gitignored — holds DB creds + all site-specific config; see .env.example).
env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_INSECURE_KEY = 'django-insecure-CHANGEME-set-ORTHANC_SECRET_KEY-in-env'
SECRET_KEY = env('ORTHANC_SECRET_KEY', default=_INSECURE_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
# Default OFF — production-safe by default; flip ORTHANC_DEBUG=true only for local dev.
DEBUG = env.bool('ORTHANC_DEBUG', default=False)

# Refuse to boot in production with the placeholder secret key (a known key is a
# total auth/signing compromise — forged sessions, CSRF, signed values).
if not DEBUG and SECRET_KEY == _INSECURE_KEY:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        'ORTHANC_SECRET_KEY must be set to a strong random value when DEBUG is off '
        '(refusing to start with the insecure placeholder key).'
    )

ALLOWED_HOSTS = env.list('ORTHANC_ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# Behind the nginx/Cloudflare proxy: trust X-Forwarded-Proto so Django knows the
# request is https (MSAL redirect_uri + secure cookies depend on this).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
CSRF_TRUSTED_ORIGINS = env.list('ORTHANC_CSRF_TRUSTED_ORIGINS', default=[])

# Production hardening — applied whenever DEBUG is off (dev stays plain-http on
# localhost). Cookies are https-only, HSTS is asserted, clickjacking/MIME-sniff
# are blocked. SSL redirect is on by default but env-overridable for proxy setups
# that terminate TLS upstream and don't want Django to redirect.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SECURE_SSL_REDIRECT = env.bool('ORTHANC_SSL_REDIRECT', default=True)
    SECURE_HSTS_SECONDS = env.int('ORTHANC_HSTS_SECONDS', default=31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# Django's password-auth /admin/ is a privileged surface PARALLEL to (and bypassing)
# the Entra operator-tier model — a weak superuser password would sidestep SSO
# entirely. OFF by default; operations run through the Entra-gated console + the
# manage.py commands. Enable only for break-glass (and proxy-restrict to localhost).
ENABLE_DJANGO_ADMIN = env.bool('ORTHANC_ENABLE_DJANGO_ADMIN', default=False)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # Orthanc apps
    'ca',
    'enrollment',
    'sso',
    'console',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'orthanc.middleware.ContentSecurityPolicyMiddleware',
]

# Content-Security-Policy (defense-in-depth; see orthanc/middleware.py). Blank =
# the middleware's built-in policy ('self' + inline for the console's inline css/js).
CONTENT_SECURITY_POLICY = env('ORTHANC_CSP', default='')

ROOT_URLCONF = 'orthanc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'orthanc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('ORTHANC_DB_NAME', default='orthanc'),
        'USER': env('ORTHANC_DB_USER', default='orthanc'),
        'PASSWORD': env('ORTHANC_DB_PASSWORD', default=''),
        'HOST': env('ORTHANC_DB_HOST', default='localhost'),
        'PORT': env('ORTHANC_DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # collectstatic target; nginx serves /static/ from here

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# Orthanc fabric config
# ---------------------------------------------------------------------------
# SPIFFE trust domain baked into every issued node SVID:
#   spiffe://<TRUST_DOMAIN>/<tenant>/node/<node-id>
SPIFFE_TRUST_DOMAIN = env('ORTHANC_TRUST_DOMAIN', default='pow3rtool')

# On-disk home for the CA key material (gitignored: *.pem / *.key). Plaintext PEM,
# root-only perms, ZFS-encrypted at rest (by design — see ca/authority.py).
CA_DIR = Path(env('ORTHANC_CA_DIR', default=str(BASE_DIR / 'ca' / 'pki')))

# Issued node-cert lifetime. Short-lived by design (auto-renewed over the tunnel)
# — but until the RCON renewal loop ships, 30d keeps nodes from dying daily.
NODE_CERT_TTL_HOURS = env.int('ORTHANC_NODE_CERT_TTL_HOURS', default=720)

# Default lifetime for a freshly minted enrollment join token.
JOIN_TOKEN_TTL_MINUTES = env.int('ORTHANC_JOIN_TOKEN_TTL_MINUTES', default=60)
# Public XConnect base URL where the certless node bootstrap is served — used to
# render the copy-paste install one-liner in the console join-token UI. Set in
# the deployment env (see .env.example); empty falls back to a placeholder host.
BOOTSTRAP_URL = env('ORTHANC_BOOTSTRAP_URL', default='')


# ---------------------------------------------------------------------------
# Entra ID (Azure AD) operator SSO — confidential client, CERTIFICATE creds.
# Delegated only (openid profile email); authZ via app roles in the token.
# ---------------------------------------------------------------------------
AZURE_TENANT_ID = env('AZURE_TENANT_ID', default='')
AZURE_CLIENT_ID = env('AZURE_CLIENT_ID', default='')
AZURE_AUTHORITY = env('AZURE_AUTHORITY', default=f'https://login.microsoftonline.com/{AZURE_TENANT_ID}')
AZURE_REDIRECT_URI = env('AZURE_REDIRECT_URI', default='http://localhost:8099/oidc/callback')
# Cert credential: private key stays here; only the public cert is in the app reg.
AZURE_CLIENT_CERT_KEY = env('AZURE_CLIENT_CERT_KEY', default='entra/orthanc-sso-key.pem')
AZURE_CLIENT_CERT_THUMBPRINT = env('AZURE_CLIENT_CERT_THUMBPRINT', default='')
# OIDC scopes we ask for — deliberately NO Graph (User.Read) and NO app permissions.
AZURE_SCOPES = env.list('AZURE_SCOPES', default=[])  # MSAL adds openid/profile/offline_access

# ---------------------------------------------------------------------------
# OBO token re-validation at the control plane (run_control).
# XConnect forwards the OBO bearer it validated; Orthanc INDEPENDENTLY verifies it
# (tenant JWKS + audience + issuer + expiry + scope) and derives the principal
# from the verified token — so a compromised XConnect can't fabricate an identity.
# OBO_AUDIENCE is the XConnect *API* app's audience (app-id GUID or api:// URI),
# NOT the Orthanc SSO app above. Enforcement auto-enables once OBO_AUDIENCE is set;
# run_control refuses to start if enforcement is on but tenant/audience are missing.
# ---------------------------------------------------------------------------
OBO_AUDIENCE = env('ORTHANC_OBO_AUDIENCE', default='')
OBO_TENANT_ID = env('ORTHANC_OBO_TENANT_ID', default=AZURE_TENANT_ID)
OBO_REQUIRED_SCOPE = env('ORTHANC_OBO_REQUIRED_SCOPE', default='tunnel.invoke')
OBO_VALIDATE_TOKEN = env.bool('ORTHANC_OBO_VALIDATE_TOKEN', default=bool(OBO_AUDIENCE))

# Fail CLOSED in production: with DEBUG off, independent OBO re-validation is
# mandatory. Without it the control plane trusts XConnect's asserted principal AND
# azp verbatim — a compromised broker could fabricate any identity and walk through
# the agent jail. Mirrors the SECRET_KEY guard above; the assertion-trust path is
# strictly a local-dev convenience (ORTHANC_DEBUG=true).
if not DEBUG and not OBO_VALIDATE_TOKEN:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        'OBO token re-validation is required when DEBUG is off: set '
        'ORTHANC_OBO_AUDIENCE (and ORTHANC_OBO_TENANT_ID) so the control plane '
        'independently verifies the forwarded OBO token instead of trusting '
        "XConnect's asserted principal/azp. For LOCAL DEV ONLY, set ORTHANC_DEBUG=true."
    )

# Map the token's `roles` claim (app roles) to Orthanc's coarse operator tiers.
# Anything unmapped is treated as no access (default-deny).
SSO_ROLE_CLAIMS = {
    'orthanc.admin': 'admin',
    'orthanc.approver': 'approver',
    'orthanc.viewer': 'viewer',
}

LOGIN_URL = '/oidc/login'
LOGIN_REDIRECT_URL = '/'  # the SSO landing (sso.views.home), NOT Django's /admin/ realm
