# Generated by Django 5.1.15 on 2026-06-22 02:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator(message='tenant slug must be 2-40 chars, lowercase alnum/hyphen, no leading/trailing hyphen', regex='^[a-z0-9][a-z0-9-]{0,38}[a-z0-9]$')])),
                ('name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JoinToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('revoked', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_tokens', to='enrollment.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('revoked', 'Revoked'), ('denied', 'Denied')], db_index=True, default='pending', max_length=10)),
                ('spki_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('csr_pem', models.TextField()),
                ('requested_name', models.CharField(blank=True, max_length=255)),
                ('src_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('bound_name', models.CharField(blank=True, max_length=255)),
                ('cert_pem', models.TextField(blank=True)),
                ('cert_serial', models.CharField(blank=True, max_length=64)),
                ('cert_not_after', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=200)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by', models.CharField(blank=True, max_length=200)),
                ('join_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='enrollment.jointoken')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='enrollment.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'state'], name='enrollment__tenant__d0902b_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'spki_fingerprint'), name='uniq_tenant_spki')],
            },
        ),
    ]
