# Generated by Django 5.1.15 on 2026-06-22 16:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=40)),
                ('spiffe_id', models.CharField(max_length=255, unique=True)),
                ('spki_fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('cert_pem', models.TextField(blank=True)),
                ('cert_not_after', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_identities', to='enrollment.tenant')),
            ],
        ),
    ]
