# Generated by Django 5.1.15 on 2026-06-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_systemidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemidentity',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
