# Generated by Django 5.1.15 on 2026-06-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_systemidentity_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='last_tunnel_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
