# Generated by Django 5.1.15 on 2026-06-22 20:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_enrollment_last_tunnel_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_kind', models.CharField(choices=[('user', 'User (UPN)'), ('group', 'Group')], default='user', max_length=8)),
                ('subject', models.CharField(max_length=255)),
                ('verb_class', models.CharField(choices=[('read', 'Read-only'), ('run', 'Run'), ('full', 'Full')], default='run', max_length=8)),
                ('require_confirmation', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='enrollment.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'subject'], name='enrollment__tenant__36051c_idx')],
            },
        ),
    ]
