# Generated by Django 5.1.15 on 2026-06-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
