# Generated by Django 5.1.15 on 2026-06-23 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0006_enrollment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='update_channel',
            field=models.CharField(db_index=True, default='stable', max_length=64),
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=64)),
                ('goos', models.CharField(max_length=32)),
                ('goarch', models.CharField(max_length=32)),
                ('sha256', models.CharField(max_length=64)),
                ('signature', models.TextField()),
                ('size', models.BigIntegerField(default=0)),
                ('blob_path', models.CharField(max_length=512)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'indexes': [models.Index(fields=['goos', 'goarch'], name='enrollment__goos_283bc2_idx')],
                'unique_together': {('version', 'goos', 'goarch')},
            },
        ),
        migrations.CreateModel(
            name='ChannelTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(db_index=True, max_length=64)),
                ('goos', models.CharField(max_length=32)),
                ('goarch', models.CharField(max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_targets', to='enrollment.release')),
            ],
            options={
                'unique_together': {('channel', 'goos', 'goarch')},
            },
        ),
    ]
