# Generated by Django 5.1.15 on 2026-06-24 02:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0007_enrollment_update_channel_release_channeltarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('oid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('tid', models.CharField(blank=True, max_length=64)),
                ('upn', models.CharField(blank=True, max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('seen_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['upn', 'oid'],
            },
        ),
        migrations.AlterField(
            model_name='grant',
            name='verb_class',
            field=models.CharField(choices=[('readonly', 'Read-only'), ('full', 'Full')], default='readonly', max_length=8),
        ),
        migrations.AddField(
            model_name='grant',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='enrollment.principal'),
        ),
    ]
