# Generated by Django 5.1.15 on 2026-06-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0009_remap_verb_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='last_report_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='running_goarch',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='running_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='update_requested',
            field=models.BooleanField(default=False),
        ),
    ]
