# Generated by Django 5.1.15 on 2026-06-25 02:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0010_enrollment_last_report_at_enrollment_running_goarch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='role',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='NodeKnowledge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=64)),
                ('content', models.TextField()),
                ('source', models.CharField(choices=[('operator', 'Operator (console)'), ('agent', 'Agent (OBO)'), ('fabric', 'Fabric (system)'), ('external', 'External')], default='agent', max_length=10)),
                ('author_oid', models.CharField(blank=True, max_length=64)),
                ('author_upn', models.CharField(blank=True, max_length=255)),
                ('trust_tier', models.CharField(default='agent', max_length=10)),
                ('critical', models.BooleanField(default=False)),
                ('severity', models.CharField(blank=True, max_length=16)),
                ('state', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('retracted', 'Retracted')], db_index=True, default='active', max_length=10)),
                ('retract_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='enrollment.enrollment')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='enrollment.nodeknowledge')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='enrollment.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'node', 'state'], name='enrollment__tenant__cc7361_idx'), models.Index(fields=['tenant', 'state', 'critical'], name='enrollment__tenant__9f9393_idx')],
            },
        ),
    ]
