# Generated by Django 5.1.15 on 2026-06-27 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0011_enrollment_role_nodeknowledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('principal_upn', models.CharField(blank=True, db_index=True, max_length=255)),
                ('principal_oid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('principal_tid', models.CharField(blank=True, max_length=64)),
                ('verb', models.CharField(blank=True, max_length=32)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('target_svid', models.CharField(blank=True, max_length=255)),
                ('allowed', models.BooleanField(db_index=True, default=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('detail', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_events', to='enrollment.tenant')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['tenant', '-occurred_at'], name='enrollment__tenant__18e5c6_idx'), models.Index(fields=['tenant', 'allowed', '-occurred_at'], name='enrollment__tenant__356b38_idx'), models.Index(fields=['tenant', 'principal_oid', '-occurred_at'], name='enrollment__tenant__aa0edd_idx')],
            },
        ),
    ]
