# Generated by Django 5.1.15 on 2026-06-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0012_callevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='callevent',
            name='duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callevent',
            name='http_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callevent',
            name='output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='callevent',
            name='output_truncated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='callevent',
            name='rc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
