# Generated by Django 5.1.15 on 2026-06-30 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0013_callevent_duration_ms_callevent_http_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callevent',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='InFlightCall',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=64, unique=True)),
                ('instance_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('principal_upn', models.CharField(blank=True, max_length=255)),
                ('principal_oid', models.CharField(blank=True, max_length=64)),
                ('principal_tid', models.CharField(blank=True, max_length=64)),
                ('verb', models.CharField(blank=True, max_length=32)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('target_svid', models.CharField(blank=True, max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('system_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inflight_calls', to='enrollment.systemidentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inflight_calls', to='enrollment.tenant')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['tenant', '-started_at'], name='enrollment__tenant__e4c0bc_idx'), models.Index(fields=['system_identity', 'instance_id'], name='enrollment__system__5edf8f_idx')],
            },
        ),
    ]
