# Generated by Django 5.1.15 on 2026-06-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0014_callevent_request_id_inflightcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='callevent',
            name='principal_app',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='callevent',
            name='principal_app_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='inflightcall',
            name='principal_app',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='inflightcall',
            name='principal_app_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
