# Generated by Django 5.1.15 on 2026-06-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0015_callevent_principal_app_callevent_principal_app_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name', 'app_id'],
            },
        ),
    ]
