# Generated by Django 5.1.15 on 2026-06-30 21:24

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0016_agentapp'),
    ]

    operations = [
        # The trigram index below uses gin_trgm_ops, which needs the pg_trgm
        # extension. pg_trgm is a "trusted" extension (PG13+), so a DB owner can
        # create it without superuser. If your DB role can't, have a DBA run
        # `CREATE EXTENSION pg_trgm;` once, then re-run migrate.
        TrigramExtension(),
        migrations.AddIndex(
            model_name='callevent',
            index=django.contrib.postgres.indexes.GinIndex(fields=['detail'], name='callevent_detail_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
