# Generated by Django 5.1.15 on 2026-06-30 22:11

from django.db import migrations, models


def grandfather_existing_approved(apps, schema_editor):
    """Agents already discovered BEFORE the jail existed were operating fine, so
    approve them on rollout — only genuinely-new harnesses get jailed. (At rollout
    this is just the pre-seeded Turnstone-MCP.)"""
    AgentApp = apps.get_model("enrollment", "AgentApp")
    AgentApp.objects.update(state="approved")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0017_callevent_callevent_detail_trgm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentapp',
            options={'ordering': ['state', 'name', 'app_id']},
        ),
        migrations.AddField(
            model_name='agentapp',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], db_index=True, default='pending', max_length=10),
        ),
        migrations.RunPython(grandfather_existing_approved, noop_reverse),
    ]
