# Generated by Django 5.1.15 on 2026-06-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upn', models.EmailField(max_length=254, unique=True)),
                ('oid', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('tier', models.CharField(choices=[('viewer', 'Viewer'), ('approver', 'Approver'), ('admin', 'Admin')], default='viewer', max_length=10)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
